# Generated by Django 3.1.3 on 2020-11-19 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='added_date',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 12, 3)),
        ),
        migrations.AlterField(
            model_name='task',
            name='added_date',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 12, 3)),
        ),
    ]
